sudo: required
language: python
os: linux
dist: xenial          # required for Python >= 3.7

matrix:
  include:
    - stage: lint
      python: 3.7
      name: 'lint'
      script: 
        - pip install -r requirements.txt
        - pip install pylint
        - pylint -rn --errors-only ./Hologram
    
    - stage: test
      python: 3.7
      name: 'test python 3'
      script:      
        - pip install .
        - pip install coveralls
        - rm -r tests/radius
        - coverage run --source Hologram -m py.test
        - coveralls

notifications:
  email: false
  slack:
    rooms:
      secure: wzP86BJJEFjs3dtALZ5tfjM4FqGL7oucXRxhVvyaG8uDH6S01q5xn6d/8jnGWgLWZAdrbAiOVMKeyMiuPq7N3puW5fVaKniVPl9wkRCaoMG0aw+qkQaKP9V0bv7Iq3sAO0HufeB2AbwOekv+wCtjZfaFFzZQqIILOdvzQfeWL+uJC0Nx2hF3q1ahDm0Twit6U7h5SLm+H9aAx2/DFKPxzQNh/8XldkinbwLne86lT+DHOIb+ak9lPzqICkme1zO3Mf1NbQTNI8Ys3Yzw2XNr/MnySj2W4qqqtVoCIgDy6AFBpRFvyb8o1NUN7yKK3xHXp5RtAKBNXPSF7Zn4ywdnvqzvV3wzz5+xPHI36fa8tDR6/Nbe2wupevp8OhMbzKUXSVK4iLoWbx+zU6qM298GvMj0zOyQJE5OFMk0jfA2ZF3xt2Po1klLtLGKebSD3I6eGQh2Xvy3Ckw8kIvpgPKnNY6Dmdm8VZ2p1hUf7jv0CYnROyKxXjXo6JOSiolfH88F4iKPg/h1459wa9CSk3OWsQHmYoE1EtshRBwPv9PfaHF60hUdfmrR1N8I+oV0Ffm9a6Y26SZVv37s4k65cBRC4AfiLmnIITAS+wt2WPf3bXhMq+338wIL0f1djUMCIu4h3OWuwLfNtardOu1WR+eb15hrCd0Kf6rRYiD9mgeqtsE=
